=== LK8000/LK8000/Common/Data/Dialogs/Dialog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="enumDataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="double" />
      <xs:enumeration value="enum" />
      <xs:enumeration value="filereader" />
      <xs:enumeration value="string" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dialog" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumBool">
    <xs:restriction base="xs:byte">
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string128">
    <xs:restriction base="xs:string">
      <xs:maxLength value="127" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string64">
    <xs:restriction base="xs:string">
      <xs:maxLength value="63" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attribute name="X" type="xs:integer" />
  <xs:attribute name="Y" type="xs:integer" />
  <xs:attribute name="Height" type="xs:integer" />
  <xs:attribute name="Width" type="xs:integer" />
  <xs:attribute name="Step" type="xs:decimal" />
  <xs:attribute name="ReadOnly" type="enumBool" />
  <xs:attribute name="Keyboard" type="enumBool" />
  <xs:attribute name="Visible" type="enumBool" />
  <xs:attribute name="Type" type="enumType" />
  <xs:attribute name="Tag" type="xs:byte" />
  <xs:attribute name="Popup" type="enumBool" />
  <xs:attribute name="OnPaint" type="xs:string" />
  <xs:attribute name="OnListInfo" type="xs:string" />
  <xs:attribute name="OnHelp" type="xs:string" />
  <xs:attribute name="OnDataAccess" type="xs:string" />
  <xs:attribute name="OnClickNotify" type="xs:string" />
  <xs:attribute name="MultiLine" type="enumBool" />
  <xs:attribute name="Min" type="xs:decimal" />
  <xs:attribute name="Max" type="xs:decimal" />
  <xs:attribute name="Help" type="xs:string" />
  <xs:attribute name="Font" type="xs:byte" />
  <xs:attribute name="EditFormat" type="xs:string" />
  <xs:attribute name="DisplayFormat" type="xs:string" />
  <xs:attribute name="Captionwidth" type="xs:integer" />
  <xs:attribute name="Border" type="xs:byte" />
  <xs:attribute name="BackColor" type="xs:integer" />
  <xs:attribute name="DataType" type="enumDataType" />
  <xs:attribute name="Name" type="string64" />
  <xs:attribute name="CaptionWidth" type="xs:integer" />
  <xs:attribute name="Caption" type="string128" />
  <xs:attribute name="Modal" type="enumBool" />
  
  <xs:element name="WndProperty">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="DataField" minOccurs="0"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="Keyboard"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnHelp"/>
      <xs:attribute ref="MultiLine"/>
      <xs:attribute ref="Help"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="CaptionWidth"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndOwnerDrawFrame">
    <xs:complexType>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnPaint"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndListFrame">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element ref="WndOwnerDrawFrame"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnListInfo" use="required"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndFrame">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Visible"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="Border"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndForm">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Type" use="required"/>
      <xs:attribute ref="Popup"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="BackColor"/>
      <xs:attribute ref="Modal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndButton">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Caption" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Tag"/>
      <xs:attribute ref="OnClickNotify"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PMML">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="WndForm" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DataField">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnDataAccess"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="EditFormat"/>
      <xs:attribute ref="DisplayFormat"/>
      <xs:attribute ref="DataType"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LK8000/LK8000/Common/Data/Dialogs/dlgWaypointEdit_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmWaypointEdit" Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="_@M795_" Font="2" >
    <WndButton   Caption="_@M186_"    X="5" Y="270" Width="60"  Height="28" Font="2" OnClickNotify="OnCloseClicked"/>
    <WndButton Name="cmdName" Caption="_@M452_" X="2" Y="0" Width="230"  Height="28" Font="2" Tag="4" />
    <WndButton Name="cmdComment" Caption="_@M191_" X="2" Y="-1" Width="230"  Height="28" Font="2" Tag="4" />
    <WndProperty Name="prpLatitudeSign" Caption="_@M1232_" X="2" Y="70" Width="65" Height="28" CaptionWidth="28" Font="2" >
      <DataField Name="" DataType="enum" Min="0" Max="1" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLatitudeD" Caption=" " X="65" Y="70" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fd" EditFormat="%.0f" Min="0" Max="89" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLatitudeM" Caption=" " X="125" Y="70" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fm" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLatitudeDDDD" Caption=" " X="125" Y="70" Width="90" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%05.0fm" EditFormat="%05.0f" Min="0" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLatitudeS" Caption=" " X="185" Y="70" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fs" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLatitudemmm" Caption=" " X="185" Y="70" Width="80" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0f" EditFormat="%.0f" Min="0" Max="999" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudeSign" Caption="_@M1234_" X="2" Y="100" Width="65" Height="28" CaptionWidth="28" Font="2" >
      <DataField Name="" DataType="enum" Min="0" Max="1" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudeD" Caption=" " X="65" Y="100" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fd" EditFormat="%.0f" Min="0" Max="179" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudeM" Caption=" " X="125" Y="100" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fm" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudeDDDD" Caption=" " X="125" Y="100" Width="90" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%05.0fm" EditFormat="%05.0f" Min="0"  Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudeS" Caption=" " X="185" Y="100" Width="60" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0fs" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpLongitudemmm" Caption=" " X="185" Y="100" Width="80" Height="28" CaptionWidth="10" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0f" EditFormat="%.0f" Min="0" Max="999" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpAltitude" Caption="_@M89_" X="2" Y="-1" Width="180" Height="28" CaptionWidth="90" Font="2" Keyboard="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0f %s" EditFormat="%.0f" Min="0" Max="30000" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpFlags" Caption="_@M752_"      X="2" Y="-1"   Width="180" Height="28" CaptionWidth="90" Font="2" >
      <DataField Name="" DataType="enum" Min="0" Max="10" Step="1" />
    </WndProperty>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgAirspaceSelect_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmAirspaceSelect" Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="_@M591_" Font="2" >

    <WndButton Name="cmdSelect" Caption="_@M595_" X="4" Y="2" Width="114"  Height="28" Font="2" Tag="3" />
    <WndButton Name="cmdClose" Caption="_@M186_" X="118" Y="2" Width="114"  Height="28" Font="2" Tag="3" />
    
	<WndFrame X="20" Y="33" Width="80" Height="18" Font="2" Caption="_@M287_" />
    <WndButton Name="cmdName" Caption="*" X="20" Y="48" Width="86"  Height="22" Font="2" />
	
    <WndProperty Name="prpFltType" Caption="_@M752_" X="118" Y="32"  Width="114" Height="40" CaptionWidth="0" Font="2" >
      <DataField Name="" DataType="string" DisplayFormat="%s" EditFormat="%s" OnDataAccess="OnFilterType"/>
    </WndProperty>
	
    <WndProperty Name="prpFltDistance"  Caption="_@M245_"  X="4" Y="74"  Width="114" Height="40" CaptionWidth="0" Font="2" >
      <DataField Name="" DataType="string" DisplayFormat="%s" EditFormat="%s" OnDataAccess="OnFilterDistance"/>
    </WndProperty>
    <WndProperty Name="prpFltDirection" Caption="_@M238_" X="118" Y="74"  Width="114" Height="40" CaptionWidth="0" Font="2" >
      <DataField Name="" DataType="string" DisplayFormat="%s" EditFormat="%s" OnDataAccess="OnFilterDirection"/>
    </WndProperty>
    <WndListFrame Name="frmAirspaceList" X="1" Y="116" Width="-1" Height="-1" Font="2" OnListInfo="OnWpListInfo">
      <WndOwnerDrawFrame Name="frmAirspaceListEntry" X="2" Y="2" Width="-2" Height="18" Font="2"  OnPaint="OnPaintListItem"/>
    </WndListFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgTarget_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmTarget" Type="Dialog" X="0" Y="0" Width="240" Height="168" Caption="_@M684_" Font="2"  Popup="1" Modal="0">
    <!-- Row 1: OK + task point (Approach moved to row 2 — full-width tap target on Kobo portrait) -->
    <WndButton  Name="btnOK" Caption="OK" X="2" Y="2" Width="50"  Height="22" Font="2" OnClickNotify="OnOKClicked" Tag="1"/>
    <WndProperty Name="prpTaskPoint" Caption="_@M689_" X="54" Y="2"   Width="184" Height="22" CaptionWidth="60" Font="2" Help="_@H460_">
      <DataField Name="" DataType="enum" Min="0" Max="50" Step="1" OnDataAccess="OnTaskPointData"/>
    </WndProperty>
    <WndButton  Name="btnApproach" Caption="_@M002516_" X="2" Y="25" Width="236" Height="22" Font="2" OnClickNotify="OnTargetApproachClicked" Tag="1"/>
    <WndButton Name="btnPrev"     Caption="&lt;" X="2"   Y="48" Width="78" Height="22" Font="2" OnClickNotify="OnPrevClicked"    Tag="1"/>
    <WndButton Name="btnNext"     Caption="&gt;" X="81"  Y="48" Width="78" Height="22" Font="2" OnClickNotify="OnNextClicked"    Tag="1"/>
    <WndButton Name="btnDirectTo" Caption="_@M002521_"  X="160" Y="48" Width="78" Height="22" Font="2" OnClickNotify="OnDirectToClicked" Tag="1"/>

    <WndProperty Name="prpRange" Caption="_@M543_" X="2" Y="48" Width="115" Height="22" CaptionWidth="50" Font="2" Help="_@H461_">
      <DataField Name="" DataType="double" DisplayFormat="%.0f%%" EditFormat="%.0f" Min="-100" Max="100" Step="5" OnDataAccess="OnRangeData"/>
    </WndProperty>
    <WndProperty Name="prpRadial" Caption="_@M541_" X="120" Y="48" Width="115" Height="22" CaptionWidth="50" Font="2" Help="_@H462_">
      <DataField Name="" DataType="double" DisplayFormat="%.0f°" EditFormat="%.0f" Min="-92" Max="92" Step="5" OnDataAccess="OnRadialData"/>
    </WndProperty>
	<WndProperty Name="prpAATEst" Caption="_@M247_" X="2" Y="73"  Width="115" Height="22" CaptionWidth="50" Font="2" ReadOnly="1" Min="0" Max="600" Step="10">
      <DataField Name="" DataType="double" DisplayFormat="%.0f min" EditFormat="%.0f" ReadOnly="1"/>
    </WndProperty>
    <WndProperty Name="prpAATDelta" Caption="delta T" X="120" Y="73"  Width="115" Height="22" CaptionWidth="50" Font="2" ReadOnly="1" Min="0" Max="600" Step="10">
      <DataField Name="" DataType="double" DisplayFormat="%.0f min" EditFormat="%.0f" ReadOnly="1"/>
    </WndProperty>
    <WndProperty Name="prpSpeedRemaining" Caption="_@M773_" X="2" Y="98"  Width="115" Height="22" CaptionWidth="50" Font="2" ReadOnly="1" Min="0" Max="2000" Step="10" >
      <DataField Name="" DataType="double" DisplayFormat="%.0f %s" EditFormat="%.1f" ReadOnly="1"/>
    </WndProperty>
    <WndProperty Name="prpSpeedAchieved" Caption="_@M772_" X="120" Y="98"  Width="115" Height="22" CaptionWidth="50" Font="2" ReadOnly="1" Min="0" Max="2000" Step="10" >
      <DataField Name="" DataType="double" DisplayFormat="%.0f %s" EditFormat="%.1f" ReadOnly="1"/>
    </WndProperty>
	<WndButton  Name="btnMove" Caption="_@M444_"    X="2" Y="123" Width="50"  Height="22" Font="2" OnClickNotify="OnMoveClicked" Tag="1"/>
    <WndProperty Name="prpAATTargetLocked" Caption="_@M683_" X="90" Y="123"  Width="145" Height="22" CaptionWidth="80" Font="2" ReadOnly="0" Help="_@H463_">
      <DataField Name="" DataType="boolean" ReadOnly="0" OnDataAccess="OnLockedData"/>
    </WndProperty>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgStatus.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Type="Dialog" X="5" Y="5" Width="240" Height="231" Caption="_@M660_" Popup="1" Font="2" >
    <WndButton Name="cmdNext"  Caption="&gt;" X="157" Y="2" Width="55"  Height="28" Font="3" OnClickNotify="OnNextClicked" Tag="1" />
    <WndButton Name="cmdPrev"  Caption="&lt;" X="82" Y="2" Width="55"  Height="28" Font="3" OnClickNotify="OnPrevClicked" Tag="0"/>
    <WndButton Name="cmdClose" Caption="_@M186_" X="2" Y="2" Width="60"  Height="28" Font="2" Tag="3" />
    <WndFrame Name="frmStatusFlight" X="0" Y="32" Width="236" Height="200" Font="2">
      <WndProperty Name="prpCoordinate"  Caption="_@M2133_"  X="2" Y="-1" Width="250" Height="22" CaptionWidth="60" Font="2" ReadOnly="1" />
      <WndProperty Name="prpAltitude"  Caption="_@M89_"  X="2" Y="-1" Width="250" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpMaxHeightGain"  Caption="_@M429_"  X="2" Y="-1" Width="250" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpNear"      Caption="_@M456_"      X="2" Y="-1" Width="250" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpBearing"   Caption="_@M138_"   X="2" Y="-1" Width="250" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpDistance"  Caption="_@M245_"   X="2" Y="-1" Width="250" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
    </WndFrame>
    <WndFrame Name="frmStatusSystem" X="0" Y="32" Width="230" Height="200" Font="2">
      <WndProperty Name="prpGPS"       Caption="_@M319_"       X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpNumSat"    Caption="_@M578_"   X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpVario"     Caption="_@M784_"     X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpFLARM"       Caption="FLARM"       X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpLogger"    Caption="_@M409_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpDeclared"    Caption="_@M223_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpBattery"       Caption="_@M672_"       X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpVersion"       Caption="Software version"       X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
    </WndFrame>
    <WndFrame Name="frmStatusTask" X="0" Y="32" Width="230" Height="200" Font="2">
      <WndProperty Name="prpTaskTime" Caption="_@M101_" X="2" Y="-1"  Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpETETime"  Caption="_@M267_"  X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpRemainingTime"  Caption="_@M549_"  X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpTaskDistance"      Caption="_@M695_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpRemainingDistance"      Caption="_@M548_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpEstimatedSpeed"      Caption="_@M630_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpAverageSpeed"      Caption="_@M629_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
    </WndFrame>
    <WndFrame Name="frmStatusRules" X="0" Y="32" Width="230" Height="200" Font="2">
      <WndProperty Name="prpValidStart"      Caption="_@M777_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpStartTime"    Caption="_@M654_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpStartHeight"      Caption="_@M638_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpStartPoint"      Caption="_@M647_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpStartSpeed"      Caption="_@M653_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpFinishAlt" Caption="_@M291_" X="2" Y="-1"  Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpValidFinish"      Caption="_@M776_"      X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
    </WndFrame>
    <WndFrame Name="frmStatusTimes" X="0" Y="32" Width="230" Height="200" Font="2">
      <WndProperty Name="prpLocalTime"    Caption="_@M402_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpFlightTime"    Caption="_@M306_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpTakeoffTime"    Caption="_@M680_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpLandingTime"    Caption="_@M386_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpSunset"    Caption="_@M671_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
    </WndFrame>
    <WndFrame Name="frmStatusExtDevice" X="0" Y="32" Width="230" Height="200" Font="2">
      <WndProperty Name="prpBattBank"    Caption="_@M134_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpBatt1Volt"    Caption="_@M132_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
      <WndProperty Name="prpBatt2Volt"    Caption="_@M133_"    X="2" Y="-1" Width="235" Height="22" CaptionWidth="120" Font="2" ReadOnly="1" />
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgRadioSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmRadioSettingRegular" Type="Dialog" X="5" Y="5" Width="230" Height="220" Caption="_@M2307_" Popup="1" Font="2" >  
    <WndButton Caption="_@M186_" X="10" Y="160" Width="210"  Height="32" Font="2" OnClickNotify="OnCancelClicked"/>
    <WndButton Name="cmdActive" Caption="*" X="10" Y="5" Width="145"  Height="32" Font="2" /> 
    <WndButton Name="cmdActiveFreq" Caption="*" X="150" Y="5" Width="60"  Height="32" Font="2" />
    <WndButton Name="cmdXchange" Caption="X" X="30" Y="45" Width="70"  Height="32" Font="2" />
    <WndButton Name="cmdDual" Caption="Dual" X="130" Y="45" Width="70"  Height="32" Font="2" />
    <WndButton Name="cmdPassive" Caption="*" X="10" Y="85" Width="145"  Height="32" Font="2" />
    <WndButton Name="cmdPassiveFreq" Caption="*" X="150" Y="85" Width="60"  Height="32" Font="2" />
    <WndButton Name="cmdVolDown" Caption="-" X="30" Y="125" Width="50"  Height="32" Font="2" />
    <WndButton Name="cmdVol" Caption="" X="90" Y="125" Width="50"  Height="32" Font="2" />
    <WndButton Name="cmdVolUp" Caption="+" X="150" Y="125" Width="50"  Height="32" Font="2" />
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgConfigPilot_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmConfiguration" Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="_@M195_" Font="2" >
    <WndButton Name="cmdClose" Caption="_@M186_" X="2" Y="270" Width="105"  Height="30" Font="2" OnClickNotify="OnCloseClicked" Tag="2" />
    <WndFrame Name="frmPilot" X="0" Y="0" Width="240" Height="269" Font="2">
      <WndProperty Caption="_@M525_" X="2" Y="-1" Width="-2" Height="44" Keyboard="1" Font="2" CaptionWidth="0">
        <DataField DataType="string" OnDataAccess="OnPilotName" />
      </WndProperty>
      <WndFrame  Caption="_@M2281_" X="2" Y="45" Width="52" Height="22" />

      <WndButton Name="cmdAdd" Caption="_@M459_" X="84" Y="45" Width="52" Height="22" Font="2" OnClickNotify="OnTrackingAddClicked" Tag="3" />
      <WndButton Name="cmdEdit" Caption="_@M252_" X="136" Y="45" Width="52" Height="22" Font="2" OnClickNotify="OnTrackingEditClicked" Tag="3" />
      <WndButton Name="cmdDelete" Caption="_@M230_" X="188" Y="45" Width="52" Height="22" Font="2" OnClickNotify="OnTrackingDeleteClicked" Tag="3" />

      <WndListFrame Name="lstTracking" X="2" Y="67" Width="-2" Height="-2" Font="2" OnListInfo="OnTrackingListInfo" >
        <WndOwnerDrawFrame Name="lstTrackingItem" X="2" Y="2" Width="-2" Height="18" Font="2" OnPaint="OnTrackingPaintListItem" />
      </WndListFrame>
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgCustomMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmSetCustommenu" Type="Dialog" X="0" Y="0" Width="240" Height="240" Caption="_@M1787_" Font="2" >
    <WndButton   Caption="_@M186_"    X="2" Y="2" Width="60"  Height="22" Font="2" OnClickNotify="OnCloseClicked" Tag="1"/>
    <WndProperty Name="prpCustomMenu1" Caption="1 " X="63" Y="-999" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu2" Caption="2 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndButton  Caption="_@M560_" X="2" Y="-1" Width="60"  Height="22" Font="2" OnClickNotify="OnResetClicked" Tag="1"/>
    <WndProperty Name="prpCustomMenu3" Caption="3 " X="63" Y="-999" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu4" Caption="4 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu5" Caption="5 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu6" Caption="6 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu7" Caption="7 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu8" Caption="8 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu9" Caption="9 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
    <WndProperty Name="prpCustomMenu10" Caption="10 " X="63" Y="-1" Width="177" Height="22" CaptionWidth="15" Font="2" Help="_@H1259_">
      <DataField Name="" DataType="enum" Min="0" Max="30" Step="1" />
    </WndProperty>
  </WndForm>
</PMML>
