=== LK8000/LK8000/Common/Data/Dialogs/Dialog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="enumDataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="double" />
      <xs:enumeration value="enum" />
      <xs:enumeration value="filereader" />
      <xs:enumeration value="string" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dialog" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumBool">
    <xs:restriction base="xs:byte">
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string128">
    <xs:restriction base="xs:string">
      <xs:maxLength value="127" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string64">
    <xs:restriction base="xs:string">
      <xs:maxLength value="63" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attribute name="X" type="xs:integer" />
  <xs:attribute name="Y" type="xs:integer" />
  <xs:attribute name="Height" type="xs:integer" />
  <xs:attribute name="Width" type="xs:integer" />
  <xs:attribute name="Step" type="xs:decimal" />
  <xs:attribute name="ReadOnly" type="enumBool" />
  <xs:attribute name="Keyboard" type="enumBool" />
  <xs:attribute name="Visible" type="enumBool" />
  <xs:attribute name="Type" type="enumType" />
  <xs:attribute name="Tag" type="xs:byte" />
  <xs:attribute name="Popup" type="enumBool" />
  <xs:attribute name="OnPaint" type="xs:string" />
  <xs:attribute name="OnListInfo" type="xs:string" />
  <xs:attribute name="OnHelp" type="xs:string" />
  <xs:attribute name="OnDataAccess" type="xs:string" />
  <xs:attribute name="OnClickNotify" type="xs:string" />
  <xs:attribute name="MultiLine" type="enumBool" />
  <xs:attribute name="Min" type="xs:decimal" />
  <xs:attribute name="Max" type="xs:decimal" />
  <xs:attribute name="Help" type="xs:string" />
  <xs:attribute name="Font" type="xs:byte" />
  <xs:attribute name="EditFormat" type="xs:string" />
  <xs:attribute name="DisplayFormat" type="xs:string" />
  <xs:attribute name="Captionwidth" type="xs:integer" />
  <xs:attribute name="Border" type="xs:byte" />
  <xs:attribute name="BackColor" type="xs:integer" />
  <xs:attribute name="DataType" type="enumDataType" />
  <xs:attribute name="Name" type="string64" />
  <xs:attribute name="CaptionWidth" type="xs:integer" />
  <xs:attribute name="Caption" type="string128" />
  <xs:attribute name="Modal" type="enumBool" />
  
  <xs:element name="WndProperty">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="DataField" minOccurs="0"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="Keyboard"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnHelp"/>
      <xs:attribute ref="MultiLine"/>
      <xs:attribute ref="Help"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="CaptionWidth"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndOwnerDrawFrame">
    <xs:complexType>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnPaint"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndListFrame">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element ref="WndOwnerDrawFrame"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnListInfo" use="required"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndFrame">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Visible"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="Border"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndForm">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Type" use="required"/>
      <xs:attribute ref="Popup"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="BackColor"/>
      <xs:attribute ref="Modal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndButton">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Caption" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Tag"/>
      <xs:attribute ref="OnClickNotify"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PMML">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="WndForm" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DataField">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnDataAccess"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="EditFormat"/>
      <xs:attribute ref="DisplayFormat"/>
      <xs:attribute ref="DataType"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LK8000/LK8000/Common/Data/Dialogs/dlgFiles_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmAirspaceFiles" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="?" Font="2"  >
    <WndFrame X="0" Y="0" Width="100" Height="20" Font="2" />
    <WndButton   Name="cmdClose" Caption="_@M186_"    X="2" Y="2" Width="98"  Height="22" Font="2" OnClickNotify="OnCloseClicked"/>
      <WndProperty Name="prpFile1" Caption="1" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile2" Caption="2" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile3" Caption="3" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile4" Caption="4" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile5" Caption="5" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile6" Caption="6" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile7" Caption="7" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile8" Caption="8" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpFile9" Caption="9" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="15" Font="2" Help="_@H105_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1"/>
      </WndProperty>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgWayPointDetails_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmWayPointInfo" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M796_" Font="2" >
    <WndButton Name="cmdNext"  Caption="_@M460_" X="3" Y="4"   Width="65"  Height="70" Font="2" Tag="1" OnClickNotify="OnNextClicked"/>
    <WndButton Name="cmdPrev"  Caption="_@M6_"   X="3" Y="78"  Width="65"  Height="70" Font="2" Tag="0" OnClickNotify="OnPrevClicked"/>
    <WndButton Name="cmdClose" Caption="_@M186_" X="3" Y="152" Width="65"  Height="70" Font="2" Tag="3" OnClickNotify="OnCloseClicked"/>
    <WndFrame Name="frmInfos"       X="70" Y="1" Width="-1" Height="-1" Font="2">
      <WndProperty Name="prpCoordinate"  Caption="_@M918_" X="2" Y="2" Width="-1" Height="22" CaptionWidth="60" Font="2" ReadOnly="1" />
      <WndProperty Name="prpAltitude"  Caption="_@M255_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpSunset"    Caption="_@M671_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpDistance"  Caption="_@M245_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpBearing"   Caption="_@M138_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpMc0"       Caption="_@M83_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndProperty Name="prpMc2"       Caption="_@M84_" X="2" Y="-1" Width="-1" Height="22" CaptionWidth="150" Font="2" ReadOnly="1" />
      <WndListFrame Name="frmWpComment" X="2" Y="-1" Width="-1" Height="64" Font="2" OnListInfo="OnWpCommentListInfo">
        <WndOwnerDrawFrame Name="frmWpCommentEntry" X="2" Y="-1" Width="-1" Height="18" Font="2"  OnPaint="OnPaintWpCommentListItem" />
      </WndListFrame>
      <WndOwnerDrawFrame Name="frmWaypointPicto"     X="10" Y="50" Width="50" Height="50" Font="2"  OnPaint="OnPaintWaypointPicto"/>  	  
    </WndFrame>
    <WndListFrame Name="frmDetails" X="70" Y="1" Width="-1" Height="-1" Font="3"    OnListInfo="OnDetailsListInfo">
      <WndOwnerDrawFrame Name="frmDetailsEntry" X="2" Y="2" Width="-2" Height="18" Font="3"  OnPaint="OnPaintDetailsListItem"/>
    </WndListFrame>
    <WndFrame Name="frmPictures"    X="70" Y="1" Width="-1" Height="-1" Font="2">
        <WndOwnerDrawFrame Name="frmPicture" X="1" Y="0" Width="-1" Height="-1" Font="2"  OnPaint="OnPaintPicture"/>
    </WndFrame>
    <WndFrame Name="frmCommands"    X="70" Y="1" Width="-1" Height="-1" Font="2" Visible="0">
      <WndButton Name="cmdInserInTask" Caption="dynamic" X="4" Y="2" Width="-2"  Height="44" Font="2" OnClickNotify="OnInserInTaskClicked"/>
      <WndButton Name="cmdAppendInTask1" Caption="_@M1827_" X="4" Y="-1" Width="-2" Height="44" Font="2" OnClickNotify="OnAppendInTask1Clicked"/>
      <WndButton Name="cmdAppendInTask2" Caption="_@M1828_" X="4" Y="-1" Width="-2" Height="44" Font="2" OnClickNotify="OnAppendInTask2Clicked"/>
      <WndButton Name="cmdRemoveFromTask" Caption="_@M552_" X="4" Y="-1" Width="-2" Height="44" Font="2" OnClickNotify="OnRemoveFromTaskClicked"/>
      <WndButton Name="cmdReplace" Caption="dynamic" X="4" Y="-1" Width="-2"  Height="41" Font="2" OnClickNotify="OnReplaceClicked"/>
    </WndFrame>
    <WndFrame Name="frmSpecial"     X="70" Y="1" Width="-1" Height="-1" Font="2" Visible="0">
      <WndButton Name="cmdNewHome" Caption="_@M605_" X="4" Y="4" Width="-2" Height="51" Font="2" OnClickNotify="OnNewHomeClicked"/>
      <WndButton Name="cmdTeamCode" Caption="_@M604_" X="4" Y="-997" Width="-2" Height="51" Font="2" OnClickNotify="OnTeamCodeClicked"/>
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgFileSelect.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmFileSelect" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M283_" Font="2" >
    <WndButton Name="cmdClose" Caption="_@M186_" X="2" Y="0" Width="56"  Height="28" Font="2" Tag="3" OnClickNotify="OnFileCloseClicked"/>
    <WndProperty Name="prpFltType"      Caption="_@M284_"      X="60" Y="0"  Width="190" Height="28" CaptionWidth="70" Font="2" >
      <DataField Name="" DataType="enum"  Min="0" Max="50" Step="1"/>
    </WndProperty>
    <WndButton Name="cmdRefresh" Caption="_@M545_" X="252" Y="0" Width="66"  Height="28" Font="2" Tag="1" OnClickNotify="OnRefreshClicked"/>
    <WndProperty Name="prpStorageFree" Caption="_@M307_" X="2" Y="-1"  Width="98" Height="36" CaptionWidth="0" Font="2" ReadOnly="1">
      <DataField Name="" DataType="double" DisplayFormat="%.0f kb" EditFormat="%.0f" ReadOnly="1"/>
    </WndProperty>
    <WndListFrame Name="frmFileList" X="102" Y="38" Width="215" Height="192" Font="2" OnListInfo="OnFileListInfo">
      <WndOwnerDrawFrame Name="frmFileListEntry" X="2" Y="2" Width="211" Height="18" Font="2"  OnPaint="OnPaintListItem"/>
    </WndListFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgTimeGates.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmTimeGates" Type="Dialog" X="0" Y="0" Width="240" Height="240" Caption="_@M513_" Font="2" >
    <WndButton   Caption="_@M186_"    X="2" Y="2" Width="60"  Height="33" Font="2" OnClickNotify="OnCloseClicked" Tag="1"/>

    <WndProperty Name="prpPGOptimizeRoute" Caption="_@M1686_"  X="2" Y="40" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H9999_">
      <DataField DataType="boolean"/>
    </WndProperty>
    <WndProperty Name="prpGateType" Caption="_@M845_" X="2" Y="-1" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H1365_">
      <DataField DataType="enum" OnDataAccess="OnGateType"/>
    </WndProperty>

    <WndFrame Name="frmFixed" X="1" Y="-1" Width="-1" Height="178">
      <WndProperty Name="prpPGNumberOfGates" Caption="_@M748_" X="1" Y="2"  Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H530_">
        <DataField Name="" DataType="double" DisplayFormat="%.0f" EditFormat="%.0f" Min="0" Max="20" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPGOpenTimeH" Caption="_@M747_" X="1" Y="-1"   Width="200" Height="22" CaptionWidth="150" Font="2" Help="_@H531_">
        <DataField Name="" DataType="double" DisplayFormat="h %.0f" EditFormat="%.0f" Min="0" Max="23" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPGOpenTimeM" Caption=":"  X="200" Y="-999"  Width="38" Height="22" CaptionWidth="5" Font="2" Help="_@H531_">
        <DataField Name="" DataType="double" DisplayFormat="%02.0f" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPGGateIntervalTime" Caption="_@M320_" X="1" Y="-1" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H532_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f m" EditFormat="%.0f" Min="1" Max="480" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPGCloseTimeH" Caption="_@M2153_" X="1" Y="-1"   Width="200" Height="22" CaptionWidth="150" Font="2" Help="_@H1266_">
        <DataField name="" DataType="double" DisplayFormat="h %.0f" EditFormat="%.0f" Min="0" Max="23" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPGCloseTimeM" Caption=":"  X="200" Y="-999"  Width="38" Height="22" CaptionWidth="5" Font="2" Help="_@H1266_">
        <DataField name="" DataType="double" DisplayFormat="%02.0f" EditFormat="%.0f" Min="0" Max="59" Step="1"/>
      </WndProperty>
    </WndFrame>

    <WndFrame Name="frmPev" X="1" Y="-999" Width="-1" Height="178">
      <WndProperty Name="prpWaitingTime" Caption="_@M846_" X="1" Y="2" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H1366_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f m" EditFormat="%.0f" Min="0" Max="120" Step="1" OnDataAccess="OnWaitingTime"/>
      </WndProperty>
      <WndProperty Name="prpStartWindow" Caption="_@M847_" X="1" Y="-1" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H1367_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f m" EditFormat="%.0f" Min="1" Max="120" Step="1" OnDataAccess="OnStartWindow"/>
      </WndProperty>
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgFlySim.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmFlySim" Type="Dialog" X="0" Y="0" Width="320" Height="240" Font="2" BackColor="0" Caption="" >
    <WndOwnerDrawFrame Name="frmSplash" X="0" Y="2" Width="318" Height="210" Font="0" OnPaint="OnSplashPaint" />
    <WndButton Name="cmdNULL" Caption="" X="1" Y="205" Width="0"  Height="0" Font="2" Tag="3" />
    <WndButton Name="cmdFLY" Caption="_@M281_" X="1" Y="205" Width="90"  Height="30" Font="2" Tag="3" />
    <WndButton Name="cmdDUALPROFILE" Caption="_@M516_" X="93" Y="205" Width="73"  Height="30" Font="2" Tag="3" />
    <WndButton Name="cmdEXIT" Caption="_@M248_" X="166" Y="205" Width="60"  Height="30" Font="2" Tag="3" />
    <WndButton Name="cmdSIM" Caption="_@M570_" X="228" Y="205" Width="90"  Height="30" Font="2" Tag="3" />
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgLKAirspaceWarning.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmAirspaceWarning" Type="Dialog" X="1" Y="1" Width="318" Height="214" Caption="_@M66_" Popup="1" Font="2" >
    <WndProperty Name="prpReason" Caption="_@M1262_" X="2" Y="2" Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />
    <WndProperty Name="prpType" Caption="_@M752_" X="2" Y="-1"  Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />	
    <WndProperty Name="prpHDist" Caption="_@M1264_" X="2" Y="-1" Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />
    <WndProperty Name="prpVDist" Caption="_@M1265_" X="2" Y="-1" Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />
    <WndProperty Name="prpTopAlt" Caption="_@M729_" X="2" Y="-1" Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />
    <WndProperty Name="prpBaseAlt" Caption="_@M128_" X="2" Y="-1" Width="310" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" />
    <WndButton  Name="cmdAckForTime" Caption="_@M46_" X="1" Y="138" Width="148" Height="56" Font="2" OnClickNotify="OnAckForTimeClicked"/>
    <WndButton  Name="cmdClose" Caption="_@M186_" X="152" Y="138" Width="148" Height="56" Font="2" OnClickNotify="OnCloseClicked"/>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgBlueFlyConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmBlueFly" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="BlueFlyVario" Font="2" >
    <WndButton Name="cmdNext"  Caption="_@M460_" X="3" Y="94" Width="62" Height="42" OnClickNotify="OnNextClicked"/>
    <WndButton Name="cmdPrev"  Caption="_@M6_" X="3" Y="-1" Width="62" Height="42" OnClickNotify="OnPrevClicked"/>
	<WndButton Name="cmdClose" Caption="_@M186_" X="3" Y="-1" Width="62" Height="42" OnClickNotify="OnClose"/>
    <WndFrame Name="1" X="70" Y="0" Width="-246" Height="222">
	  <WndProperty Name="BQH" Caption="_@M2158_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1271_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f Pa" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BFL" Caption="_@M2159_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1272_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.02f m/s" EditFormat="%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BOL" Caption="_@M2160_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1273_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.02f m/s" EditFormat="%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BFS" Caption="_@M2161_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1274_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="-%.02f m/s" EditFormat="-%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BOS" Caption="_@M2162_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1275_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="-%.02f m/s" EditFormat="-%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BFK" Caption="_@M2163_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1276_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.02f" EditFormat="%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
	</WndFrame>
	<WndFrame Name="2" X="70" Y="0" Width="-246" Height="222">
      <WndProperty Name="BFQ" Caption="_@M2164_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1277_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f Hz" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BFI" Caption="_@M2165_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1278_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f Hz" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BSQ" Caption="_@M2166_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1279_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f Hz" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BSI" Caption="_@M2167_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1280_">
		<DataField DataType="double" DisplayFormat="%.0f Hz" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BVL" Caption="_@M2168_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1281_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.02f" EditFormat="%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BRM" Caption="_@M2169_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1282_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.02f" EditFormat="%.02f" Step="0.01" OnDataAccess="OnParamData"/>
	  </WndProperty>
	</WndFrame>
	<WndFrame Name="3" X="70" Y="0" Width="-246" Height="222">
	  <WndProperty Name="BAC" Caption="_@M2170_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1283_">
		<DataField DataType="boolean" OnDataAccess="OnParamData"/>
	  </WndProperty>
	  <WndProperty Name="BAD" Caption="_@M2171_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1284_">
		<DataField DataType="boolean" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BTH" Caption="_@M2172_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1285_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f" EditFormat="%.0f" Step="1" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BOM" Caption="_@M2173_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1286_">
		<DataField DataType="enum" OnDataAccess="OnParamData"/>
	  </WndProperty>
      <WndProperty Name="BOF" Caption="_@M2174_" CaptionWidth="170" X="2" Y="-1" Width="-246" Height="22" Help="_@H1287_" Keyboard="1">
		<DataField DataType="double" DisplayFormat="%.0f ms" EditFormat="%.0f" Step="20" OnDataAccess="OnParamData"/>
	  </WndProperty>
	</WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgAirspace_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmAirspace" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M68_" Font="2"  >
    <WndFrame X="0" Y="0" Width="100" Height="20" Font="2" />
    <WndButton   Name="cmdClose" Caption="_@M186_"    X="2" Y="2" Width="98"  Height="22" Font="2" OnClickNotify="OnCloseClicked"/>
    <WndButton   Name="cmdLookup" Caption="_@M411_"    X="2" Y="26" Width="98"  Height="22" Font="2" OnClickNotify="OnLookupClicked"/>
    <WndProperty Name="prpUsedOnly" Caption="Used only" X="2" Y="50" Width="98" Height="44" CaptionWidth="0" Font="2">
      <DataField Name="" DataType="boolean" OnDataAccess="OnFilterUsedOnly"/>
    </WndProperty>
    <WndListFrame Name="frmAirspaceList" X="102" Y="0" Width="-2" Height="222" Font="2" OnListInfo="OnAirspaceListInfo">
      <WndOwnerDrawFrame Name="frmAirspaceListEntry" X="2" Y="2" Width="-2" Height="18" Font="2"  OnPaint="OnAirspacePaintListItem"/>
    </WndListFrame>
  </WndForm>
</PMML>
