=== LK8000/LK8000/Common/Data/Dialogs/Dialog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="enumDataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="double" />
      <xs:enumeration value="enum" />
      <xs:enumeration value="filereader" />
      <xs:enumeration value="string" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dialog" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="enumBool">
    <xs:restriction base="xs:byte">
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string128">
    <xs:restriction base="xs:string">
      <xs:maxLength value="127" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string64">
    <xs:restriction base="xs:string">
      <xs:maxLength value="63" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attribute name="X" type="xs:integer" />
  <xs:attribute name="Y" type="xs:integer" />
  <xs:attribute name="Height" type="xs:integer" />
  <xs:attribute name="Width" type="xs:integer" />
  <xs:attribute name="Step" type="xs:decimal" />
  <xs:attribute name="ReadOnly" type="enumBool" />
  <xs:attribute name="Keyboard" type="enumBool" />
  <xs:attribute name="Visible" type="enumBool" />
  <xs:attribute name="Type" type="enumType" />
  <xs:attribute name="Tag" type="xs:byte" />
  <xs:attribute name="Popup" type="enumBool" />
  <xs:attribute name="OnPaint" type="xs:string" />
  <xs:attribute name="OnListInfo" type="xs:string" />
  <xs:attribute name="OnHelp" type="xs:string" />
  <xs:attribute name="OnDataAccess" type="xs:string" />
  <xs:attribute name="OnClickNotify" type="xs:string" />
  <xs:attribute name="MultiLine" type="enumBool" />
  <xs:attribute name="Min" type="xs:decimal" />
  <xs:attribute name="Max" type="xs:decimal" />
  <xs:attribute name="Help" type="xs:string" />
  <xs:attribute name="Font" type="xs:byte" />
  <xs:attribute name="EditFormat" type="xs:string" />
  <xs:attribute name="DisplayFormat" type="xs:string" />
  <xs:attribute name="Captionwidth" type="xs:integer" />
  <xs:attribute name="Border" type="xs:byte" />
  <xs:attribute name="BackColor" type="xs:integer" />
  <xs:attribute name="DataType" type="enumDataType" />
  <xs:attribute name="Name" type="string64" />
  <xs:attribute name="CaptionWidth" type="xs:integer" />
  <xs:attribute name="Caption" type="string128" />
  <xs:attribute name="Modal" type="enumBool" />
  
  <xs:element name="WndProperty">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="DataField" minOccurs="0"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="Keyboard"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnHelp"/>
      <xs:attribute ref="MultiLine"/>
      <xs:attribute ref="Help"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="CaptionWidth"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndOwnerDrawFrame">
    <xs:complexType>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnPaint"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndListFrame">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element ref="WndOwnerDrawFrame"/>
      </xs:choice>
      <xs:attribute ref="Name" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="OnListInfo" use="required"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndFrame">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Visible"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="Border"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndForm">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="WndProperty" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndButton" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndOwnerDrawFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndFrame" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="WndListFrame" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Type" use="required"/>
      <xs:attribute ref="Popup"/>
      <xs:attribute ref="Font" use="required"/>
      <xs:attribute ref="Caption"/>
      <xs:attribute ref="BackColor"/>
      <xs:attribute ref="Modal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="WndButton">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Caption" use="required"/>
      <xs:attribute ref="Y" use="required"/>
      <xs:attribute ref="X" use="required"/>
      <xs:attribute ref="Width" use="required"/>
      <xs:attribute ref="Height" use="required"/>
      <xs:attribute ref="Tag"/>
      <xs:attribute ref="OnClickNotify"/>
      <xs:attribute ref="Font" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PMML">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="WndForm" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DataField">
    <xs:complexType>
      <xs:attribute ref="Name"/>
      <xs:attribute ref="Step"/>
      <xs:attribute ref="ReadOnly"/>
      <xs:attribute ref="OnDataAccess"/>
      <xs:attribute ref="Min"/>
      <xs:attribute ref="Max"/>
      <xs:attribute ref="EditFormat"/>
      <xs:attribute ref="DisplayFormat"/>
      <xs:attribute ref="DataType"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LK8000/LK8000/Common/Data/Dialogs/dlgMultiSelectList.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmMultiSelectList" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M595_" Font="2"  >
    <WndFrame X="0" Y="0" Width="100" Height="20" Font="2" />
	<WndButton   Name="cmdUp" Caption="_@M2100_"    X="2" Y="2" Width="98"  Height="50" Font="2" OnClickNotify="OnUpClicked"/>      	
    <WndButton   Name="cmdClose" Caption="_@M186_"    X="2" Y="190" Width="98"  Height="30" Font="2" OnClickNotify="OnCloseClicked"/>
	<WndButton   Name="cmdEnter" Caption="_@M1654_"    X="2" Y="70" Width="98"  Height="50" Font="2" OnClickNotify="OnEnterClicked"/> 
	<WndButton   Name="cmdDown" Caption="_@M2102_"    X="2" Y="140" Width="98"  Height="50" Font="2" OnClickNotify="OnDownClicked"/>  
    <WndListFrame Name="frmMultiSelectListList" X="102" Y="0" Width="-215" Height="222" Font="2" OnListInfo="OnMultiSelectListListInfo">
      <WndOwnerDrawFrame Name="frmMultiSelectListListEntry" X="2" Y="2" Width="-203" Height="36" Font="2"  OnPaint="OnMultiSelectListPaintListItem"/>
    </WndListFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgConfigPilot.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmConfiguration" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M195_" Font="2" >
    <WndButton Name="cmdClose" Caption="_@M186_" X="3" Y="178" Width="62"  Height="42" Font="2" Tag="3" />
    <WndFrame Name="frmPilot" X="70" Y="10" Width="-246" Height="222" Font="2">
      <WndButton Name="cmdPilotName" Caption="_@M525_" X="2" Y="1" Width="-246"  Height="35" Font="2" />
      <WndProperty Name="prpLiveTrackerInterval" Caption="_@M1779_" X="2" Y="70" Width="236" Height="22" CaptionWidth="150" Font="2" Help="_@H1258_">
        <DataField Name="" DataType="double" DisplayFormat="%.0f %s" EditFormat="%.0f" Min="0.0" Max="60.0" Step="1.0" />
      </WndProperty>
      <WndButton Name="cmdLiveTrackersrv" Caption="_@M1782_" X="2" Y="-1" Width="200"  Height="25" Font="2" />
      <WndButton Name="cmdLiveTrackerport" Caption="Port" X="202" Y="-999" Width="35"  Height="25" Font="2" />
      <WndButton Name="cmdLiveTrackerusr" Caption="_@M1780_" X="2" Y="-1" Width="117"  Height="25" Font="2" />
      <WndButton Name="cmdLiveTrackerpwd" Caption="_@M1781_" X="120" Y="-999" Width="117"  Height="25" Font="2" />
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgWayQuick_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd" >
  <WndForm Name="frmWayQuick" Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="" Font="2" >
    <WndButton Name="cmdGoto" Caption="_@M330_" X="55" Y="2" Width="180"  Height="48" Font="2" Tag="3" OnClickNotify="OnGotoClicked" />
    <WndOwnerDrawFrame Name="frmWaypointPicto"     X="3" Y="2" Width="48" Height="48" Font="2"  OnPaint="OnPaintWaypointPicto" />  	  
    <WndButton Name="cmdSetAlt1" Caption="_@M597_" X="3" Y="-998" Width="232"  Height="39" Font="2" Tag="3" OnClickNotify="OnSetAlt1Clicked" />
    <WndButton Name="cmdSetAlt2" Caption="_@M598_" X="3" Y="-998" Width="232"  Height="39" Font="2" Tag="3" OnClickNotify= "OnSetAlt2Clicked" />
    <WndButton Name="cmdDetails" Caption="_@M231_" X="3" Y="-998" Width="232"  Height="39" Font="2" Tag="3" OnClickNotify="OnDetailsClicked" />
    <WndButton Name="cmdTask" Caption="_@M699_" X="3" Y="-998" Width="232"  Height="39" Font="2" Tag="3" OnClickNotify="OnTaskClicked" />
    <WndButton Name="cmdRadioFreqSB" Caption="_@M2174_" X="3" Y="-998" Width="115"  Height="39" Font="2" Tag="3" OnClickNotify="OnRadioFrequencySBClicked" />
    <WndButton Name="cmdRadioFreq" Caption="_@M2174_" X="119" Y="-999" Width="115"  Height="39" Font="2" Tag="3" OnClickNotify="OnRadioFrequencyClicked" />
    <WndButton Name="cmdCancel" Caption="_@M161_" X="3" Y="-998" Width="232"  Height="39" Font="2" Tag="3" OnClickNotify="OnCancelClicked" />
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgConfigAircraft_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmConfiguration" Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="_@M195_" Font="2" >
    <WndButton Name="cmdClose" Caption="_@M186_" X="5" Y="270" Width="105"  Height="30" Font="2" Tag="2" />
    <WndFrame Name="frmPolar" X="0" Y="0" Width="235" Height="222" Font="2">
      <WndProperty Name="prpAircraftCategory" Caption="_@M164_" X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" Help="_@H1205_" >
        <DataField Name="" DataType="enum" Min="0" Max="10" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpPolarFile" Caption="_@M751_" X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" Help="_@H1208_">
        <DataField Name="" DataType="filereader" Min="0" Max="200" Step="1" OnDataAccess="OnPolarFileData"/>
      </WndProperty>
      <WndProperty Name="prpMaxManoeuveringSpeed" Caption="_@M1744_" X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" Help="_@H150_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f %s" EditFormat="%.0f" Min="30" Max="300" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpHandicap" Caption="_@M334_" X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" Help="_@H151_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f " EditFormat="%.0f" Min="50" Max="150" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpBallastSecsToEmpty" Caption="_@M246_" X="2" Y="-1" Width="235" Height="22" CaptionWidth="150" Font="2" Help="_@H152_" Keyboard="1">
        <DataField Name="" DataType="double" DisplayFormat="%.0f s" EditFormat="%.0f" Min="10" Max="900" Step="1"/>
      </WndProperty>
      <WndButton Name="cmdAircraftType" Caption="_@M60_" X="2" Y="-1" Width="235"  Height="22" Font="2" />
      <WndButton Name="cmdAircraftRego" Caption="_@M56_" X="2" Y="-1" Width="235"  Height="22" Font="2" />
      <WndButton Name="cmdCompetitionClass" Caption="_@M937_" X="2" Y="-1" Width="235"  Height="22" Font="2" />
      <WndButton Name="cmdCompetitionID" Caption="_@M939_" X="2" Y="-1" Width="235"  Height="22" Font="2" />
    </WndFrame>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgBottomBar.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmSetBottomBar" Type="Dialog" X="0" Y="0" Width="240" Height="240" Caption="_@M1605_" Font="2" >
    <WndButton   Caption="_@M186_"    X="2" Y="2" Width="60"  Height="22" Font="2" OnClickNotify="OnCloseClicked" Tag="1"/>

    <WndProperty Name="prpConfBB1" Caption="_@M1341_" X="2" Y="-998" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>
    <WndProperty Name="prpConfBB6" Caption="_@M1346_" X="120" Y="-999" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>

    <WndProperty Name="prpConfBB2" Caption="_@M1342_" X="2" Y="-1" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>
    <WndProperty Name="prpConfBB7" Caption="_@M1347_" X="120" Y="-999" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>

    <WndProperty Name="prpConfBB3" Caption="_@M1343_" X="2" Y="-1" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>
    <WndProperty Name="prpConfBB8" Caption="_@M1348_" X="120" Y="-999" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>

    <WndProperty Name="prpConfBB4" Caption="_@M1344_" X="2" Y="-1" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>
    <WndProperty Name="prpConfBB9" Caption="_@M1349_" X="120" Y="-999" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>

    <WndProperty Name="prpConfBB5" Caption="_@M1345_" X="2" Y="-1" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>


    <WndProperty Name="prpConfBB0" Caption="_@M1340_" X="2" Y="-997" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1220_">
      <DataField Name="" DataType="boolean" />
    </WndProperty>
    <WndProperty Name="prpConfBB0Auto" Caption="_@M1821_" X="120" Y="-999" Width="118" Height="22" CaptionWidth="60" Font="2" Help="_@H1263_">
      <DataField Name="" DataType="enum" />
    </WndProperty>

  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgConfigDevice_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" 
  xmlns="http://www.dmg.org/PMML-3-0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Name="frmConfiguration" Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="_@M195_" Font="2">
    <WndButton Name="cmdA" Caption="A" X="1" Y="-1" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnA" />
    <WndButton Name="cmdB" Caption="B" X="51" Y="-999" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnB" />
    <WndButton Name="cmdC" Caption="C" X="101" Y="-999" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnC" />
    <WndButton Name="cmdD" Caption="D" X="151" Y="-999" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnD" />
    <WndButton Name="cmdE" Caption="E" X="201" Y="-999" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnE" />
    <WndButton Name="cmdF" Caption="F" X="251" Y="-999" Width="50" Height="40" Font="2" Tag="2" OnClickNotify="OnF" />

    <WndButton Name="cmdTerminal" Caption="_@M1871_" X="3" Y="138" Width="70" Height="28" Font="2" Tag="3" OnClickNotify="OnTerminalClicked" />
    <WndButton Name="cmdClose" Caption="_@M186_" X="3" Y="194" Width="70" Height="28" Font="2" Tag="3" OnClickNotify="OnCloseClicked" />

    <WndFrame Name="frmCommName" Caption="_@M232_" X="0" Y="40" Width="-1" Height="98" Font="2">
      <WndButton Name="cmdConfigDev" Caption="_@M2414_" X="3" Y="20" Width="50" Height="28" Font="2" Tag="3" OnClickNotify="OnConfigDevClicked" />

      <WndProperty Name="prpComDevice1" Caption="_@M450_" X="60" Y="1" Width="-1" Height="22" CaptionWidth="70" Font="2" Help="_@H153_">
        <DataField Name="" DataType="enum" OnDataAccess="OnDeviceAData" />
      </WndProperty>
      <WndProperty Name="prpComPort1" Caption="_@M530_" X="60" Y="-1" Width="195" Height="22" CaptionWidth="70" Font="2" Help="_@H154_">
        <DataField Name="" DataType="enum" Min="0" Max="50" Step="1" OnDataAccess="OnComPort1Data"/>
      </WndProperty>
      <WndProperty Name="prpExtSound1" Caption="_@M2250_" X="235" Y="-999" Width="-1" Height="22" CaptionWidth="70" Font="2" Help="_@H240_">
        <DataField Name="" DataType="boolean"/>
      </WndProperty>
      <WndButton Name="cmdReplay" Caption="_@M285_" X="130" Y="45" Width="105" Height="22" Font="2" Tag="3" OnClickNotify="OnConfigDevReplayClicked" />
      <WndProperty Name="prpComSpeed1" Caption="_@M135_" X="60" Y="45" Width="155" Height="22" CaptionWidth="70" Font="2" Help="_@H155_">
        <DataField Name="" DataType="enum" Min="0" Max="50" Step="1" />
      </WndProperty>
      <WndProperty Name="prpComBit1" Caption=" " X="215" Y="-999" Width="-1" Height="22" CaptionWidth="1" Font="2" Help="_@H156_">
        <DataField Name="" DataType="enum" Min="0" Max="50" Step="1" />
      </WndProperty>
      <WndProperty Name="prpComIpAddr1" Caption="IP" X="60" Y="-999" Width="240" Height="22" CaptionWidth="70" Font="2" Keyboard="1">
        <DataField Name="" DataType="string" DisplayFormat="%s" EditFormat="%s"/>
      </WndProperty>
      <WndProperty Name="prpComIpPort1" Caption="Port" X="250" Y="-999" Width="-1" Height="22" CaptionWidth="30" Font="2" Keyboard="1">
        <DataField Name="" DataType="integer" DisplayFormat="%d" EditFormat="%d" Min="1" Max="65635" Step="1"/>
      </WndProperty>
      <WndProperty Name="prpStatus" Caption="_@M660_" X="60" Y="70" Width="-1" Height="22" CaptionWidth="70" Font="2" ReadOnly="1" Keyboard="0">
        <DataField Name="" DataType="string" DisplayFormat="%s" EditFormat="%s"/>
      </WndProperty>
    </WndFrame>

    <WndProperty Name="prpUseGeoidSeparation" Caption="_@M322_" X="75" Y="140" Width="-1" Height="21" CaptionWidth="115" Font="2" Help="_@H158_">
      <DataField Name="" DataType="boolean"/>
    </WndProperty>
    <WndProperty Name="prpPollingMode" Caption="_@M596_" X="75" Y="-1" Width="-1" Height="21" CaptionWidth="115" Font="2" Help="_@H160_">
      <DataField Name="" DataType="enum" Min="0" Max="1" Step="1"/>
    </WndProperty>
    <WndProperty Name="prpAppInfoBoxModel" Caption="_@M234_" X="75" Y="-1" Width="-1" Height="21" CaptionWidth="115" Font="2" Help="_@H209_">
      <DataField Name="" DataType="enum" Min="0" Max="50" Step="1"/>
    </WndProperty>
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgAnalysis_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Type="Dialog" X="0" Y="0" Width="240" Height="320" Caption="_@M93_" Font="2" >
    <WndOwnerDrawFrame Name="frmGrid" X="1" Y="1" Width="-1" Height="200" Font="0" OnPaint="OnAnalysisPaint" />
    <WndOwnerDrawFrame Name="frmInfo" X="90" Y="205" Width="-1" Height="-1" Font="2" />
    <WndButton Name="cmdCalc"  Caption="_@M160_" X="1" Y="206" Width="82"  Height="28" Font="2" OnClickNotify="OnCalcClicked" />
    <WndButton Name="cmdNext"  Caption="&gt;" X="42" Y="240" Width="41"  Height="28" Font="3" OnClickNotify="OnNextClicked" Tag="1" />
    <WndButton Name="cmdPrev"  Caption="&lt;" X="1" Y="240" Width="41"  Height="28" Font="3" OnClickNotify="OnPrevClicked" Tag="0"/>
    <WndButton Name="cmdClose" Caption="_@M186_" X="1" Y="270" Width="82"  Height="28" Font="2" Tag="3" />
  </WndForm>
</PMML>

=== LK8000/LK8000/Common/Data/Dialogs/dlgDevLXNav_L.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMML version="3.0" xmlns="http://www.dmg.org/PMML-3-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema_instance" xsi:noNamespaceSchemaLocation="Dialog.xsd">
  <WndForm Type="Dialog" X="0" Y="0" Width="320" Height="240" Caption="LXNav Config" Popup="1" Font="2" >   
    <WndButton Name="cmdClose"       Caption="_@M186_"     X="2" Y="1"  Width="110"  Height="28" Font="2" Tag="3" />
    <WndButton Name="cmdCancel"      Caption="_@M161_"     X="2" Y="-1"  Width="110"  Height="28" Font="2" Tag="3" />    
    <WndButton Name="cmdIGCDownload" Caption="_@M2398_"    X="120" Y="1" Width="110"  Height="28" Font="2" Tag="3" />                          
    <WndButton Name="cmdValues" Caption="_@M2447_"    X="120" Y="-1" Width="110"  Height="28" Font="2" Tag="3" />
    
     <WndProperty Name="prpMCDir" Caption="_@M2427_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="3" Step="1"/>
      </WndProperty> 
      <WndProperty Name="prpTARGDir" Caption="_@M2438_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>        
      </WndProperty>                  
     <WndProperty Name="prpBALDir" Caption="_@M2428_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="3" Step="1"/>
      </WndProperty>    
      <WndProperty Name="prpGFORCEDir" Caption="_@M2442_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>         
      <WndProperty Name="prpBUGDir" Caption="_@M2429_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="3" Step="1"/>
      </WndProperty> 
      <WndProperty Name="prpOATDir" Caption="_@M2443_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>                
      <WndProperty Name="prpSTFDir" Caption="_@M2430_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>  
      <WndProperty Name="prpBAT1Dir" Caption="_@M2444_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>             
      <WndProperty Name="prpWINDDir" Caption="_@M2431_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>  
      <WndProperty Name="prpBAT2Dir" Caption="_@M2445_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>            
      <WndProperty Name="prpBARODir" Caption="_@M2435_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty> 
      <WndProperty Name="prpPOLARDir" Caption="_@M2446_" X="130" Y="-999" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>        
      <WndProperty Name="prpSPEEDDir" Caption="_@M2436_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>       
       <WndProperty Name="prpVARIODir" Caption="_@M2437_" X="2" Y="-1" Width="120" Height="21" CaptionWidth="50" Font="2" Help="_@H1303_">
        <DataField Name="" DataType="enum"  Min="0" Max="2" Step="1"/>
      </WndProperty>    
            
        
  </WndForm>
</PMML>
